// Front-end/Angular/angular-ngrx/src/app/components/user/user.component.ts
import { Component, OnInit } from '@angular/core';
import { Store, select } from '@ngrx/store';
import { Observable } from 'rxjs';
import { setJwtToken, clearJwtToken } from '../../ngrx/actions/auth.action';
import { User } from 'src/app/models/user.model';
import { UserService } from 'src/app/services/user.service';
import { checkPasswordStrength, checkValidEmail } from 'src/app/common/helper-function';
import { NgxSpinnerService } from 'ngx-spinner';

@Component({
    selector: 'app-user',
    templateUrl: 'user.component.html'
})
export class UserComponent implements OnInit{
    constructor(private store: Store<{auth: {JwtToken: string}}>,
                private loadingService: NgxSpinnerService,
                private userService: UserService){}

    // token: Observable<{jwtToken: string}>;
    token: string;
    user: User;

    ngOnInit(){
        this.store.pipe(select("auth"))
            .subscribe(res => {
                this.token = res.JwtToken;
            })

        this.user = new User();
    }

    onSetToken(){
        this.store.dispatch(setJwtToken({payload: 'jwt token get from server'}));
        console.log(this.token);
    }

    onShowToken(){
        console.log(this.token);
    }

    onClearToken(){
        this.store.dispatch(clearJwtToken());
    }

    onRegisterUser(){
        if(this.onValidateRequire()){
            this.loadingService.show();
            this.userService.OnRegisterUser(this.user)
                .subscribe(res => {
                    console.log(res);
                    this.loadingService.hide();
                },
                err => {
                    this.loadingService.hide();
                })
        }
        else{
            this.onShowErrorMessage();
        }
    }

    onValidateRequire(){
        if(this.user.UPDATEDATE && this.user.PASSWORD && this.user.ROLE
        && this.user.ACTIVE && this.user.EMAIL && this.user.DAYOFBIRTH
        && this.user.ADDRESS && checkPasswordStrength(this.user.PASSWORD) && checkValidEmail(this.user.EMAIL))
            return true;
        return false;
    }

    onShowErrorMessage(){

    }
}
<h1>User Component</h1>
<div>
    <div>
        <label>Username: </label>
        <input type="text" [(ngModel)]="user.USERNAME" />
    </div>
    <div>
        <label>Password: </label>
        <input type="password" [(ngModel)]="user.PASSWORD" />
    </div>
    <div>
        <label>Role: </label>
        <select [(ngModel)]="user.ROLE">
            <option value="Super Admin">Super Admin</option>
            <option value="Admin">Admin</option>
            <option value="Member">Member</option>
            <option value="Guest">Guest</option>
        </select>
    </div>
    <div>
        <label>Active: </label>
        <select [(ngModel)]="user.ACTIVE">
            <option value="0">Inactive</option>
            <option value="1">Active</option>
        </select>
    </div>
    <div>
        <label>Email: </label>
        <input type="text" [(ngModel)]="user.EMAIL" />
    </div>
    <div>
        <label>DOB: </label>
        <input type="text" [(ngModel)]="user.DAYOFBIRTH" />
    </div>
    <div>
        <label>Address: </label>
        <textarea [(ngModel)]="user.ADDRESS"></textarea>
    </div>
    <div>
        <button (click)="onRegisterUser()">Register</button>
    </div>
</div>

<button (click)="onShowToken()">Show Token</button>

// Front-end/React/react-redux-thunk/src/components/user.component.js
import React, { Component } from 'react';
import { User } from '../models/user';
import UserService from '../services/user.service';
import { withRouter } from 'react-router-dom';

class UserComponent extends Component {
    constructor(props){
        super(props);

        this.state = {
            user: new User()
        }

        this.onRegister = this.onRegister.bind(this);
        this.onHandleChange = this.onHandleChange.bind(this);
    }

    async onHandleChange(event){
        let propName = event.target.name;
        let value = event.target.value;
        await this.setState(prevState => ({
            user: {
                ...prevState.user,
                [propName]: value
            }
        }))
    }

    onRegister(){
        UserService.onRegister(this.state.user)
            .then(res => {
                console.log(res);
            })
            .catch(err => {
                console.log(err);
            })
    }

    render(){
        return(
            <div>
                <h3>User Component</h3>
                <div>
                    <label>Username</label>
                    <input type='text' name='USERNAME' value={this.state.user.USERNAME} onChange={this.onHandleChange} />
                </div>
                <div>
                    <label>Password</label>
                    <input type='password' name='PASSWORD' value={this.state.user.PASSWORD} onChange={this.onHandleChange} />
                </div>
                <div>
                    <label>Role</label>
                    <select value={this.state.user.ROLE} name='ROLE' onChange={this.onHandleChange}>
                        <option value='Super Admin'>Super Admin</option>
                        <option value='Admin'>Admin</option>
                        <option value='Member'>Member</option>
                        <option value='Guest'>Guest</option>
                    </select>
                </div>
                <div>
                    <label>Active</label>
                    <select value={this.state.user.ACTIVE} name='ACTIVE' onChange={this.onHandleChange}>
                        <option value='0'>Inactive</option>
                        <option value='1'>Active</option>
                    </select>
                </div>
                <div>
                    <label>Email</label>
                    <input type='text' name='EMAIL' value={this.state.user.EMAIL} onChange={this.onHandleChange} />
                </div>
                <div>
                    <label>DOB</label>
                    <input type='date' name='DAYOFBIRTH' value={this.state.user.DAYOFBIRTH} onChange={this.onHandleChange} />
                </div>
                <div>
                    <label>Address</label>
                    <input type='text' name='ADDRESS' value={this.state.user.ADDRESS} onChange={this.onHandleChange} />
                </div>
                <div>
                    <button onClick={this.onRegister}>Register</button>
                </div>
            </div>
        )
    }
}

export default withRouter(UserComponent);
